CREATE DATABASE prisma5;
GRANT ALL PRIVILEGES ON DATABASE prisma5 TO db_user;

CREATE DATABASE prisma6;
GRANT ALL PRIVILEGES ON DATABASE prisma6 TO db_user;

CREATE DATABASE prisma7;
GRANT ALL PRIVILEGES ON DATABASE prisma7 TO db_user;
